// ----- PERMISSION CODE -----

export enum EPermission {
  // --- MANAGEMENT ---

  MANAGEMENT_FILES_CENTER = 'MANAGEMENT_FILES_CENTER',

  // --- MANAGEMENT: PROJECT ---

  PROJECT_Z_PORTFOLIO = 'PROJECT_Z_PORTFOLIO',

  DOMAIN_HUB = 'DOMAIN_HUB',
  DOMAIN_HUB_DOMAIN = 'DOMAIN_HUB_DOMAIN',
  DOMAIN_HUB_CERTIFICATION = 'DOMAIN_HUB_CERTIFICATION',
  DOMAIN_HUB_PUBLIC_FILE = 'DOMAIN_HUB_PUBLIC_FILE',

  // --- CONFIGURATION ---

  CONFIGURATION_ROLE = 'CONFIGURATION_ROLE',
  CONFIGURATION_USER = 'CONFIGURATION_USER',
  CONFIGURATION_PERMISSION = 'CONFIGURATION_PERMISSION',

  // --- SETTING ---

  SETTING_PROFILE = 'SETTING_PROFILE',
  SETTING_RESET_PASSWORD = 'SETTING_RESET_PASSWORD',

  // --- OTHERS ---

  FEEDBACK = 'FEEDBACK',
}

// ----- PERMISSION ACTION -----

export enum EPermissionAction {
  CREATE = 1 << 0,
  READ = 1 << 1,
  UPDATE = 1 << 2,
  DELETE = 1 << 3,
}

// ----- PERMISSION STATUS -----

export enum EPermissionStatus {
  ENABLED = 1,
  DISABLED = 2,
}
