// ----- PERMISSION CODE -----

export enum EPermission {
  APP_OVERVIEW = 'APP_OVERVIEW',

  PROJECT_PORTFOLIO = 'PROJECT_PORTFOLIO',

  GENERAL = 'GENERAL',
  ACCOUNT = 'ACCOUNT',
  FEEDBACK = 'FEEDBACK',

  ADMINISTRATION = 'ADMINISTRATION',
  USER_CONFIGURE = 'USER_CONFIGURE',
  APPLICATION_CONFIGURE = 'APPLICATION_CONFIGURE',
  PERMISSION_CONFIGURE = 'PERMISSION_CONFIGURE',
  ROLE_CONFIGURE = 'ROLE_CONFIGURE',

  APP_KEY_MANAGEMENT = 'APP_KEY_MANAGEMENT',
  APP_KEY_CONFIGURE = 'APP_KEY_CONFIGURE',

  // PROJECTS
  PORTFOLIO = 'PORTFOLIO',
}

// ----- PERMISSION ACTION -----

export enum EPermissionAction {
  CREATE = 1 << 0,
  READ = 1 << 1,
  UPDATE = 1 << 2,
  DELETE = 1 << 3,
}

// ----- PERMISSION STATUS -----

export enum EPermissionStatus {
  ENABLED = 1,
  DISABLED = 2,
}

export enum EPermissionCategory {
  DASHBOARD = 1,
  CATALOG = 2,
  CONFIGURATION = 3,
  TOOL = 4,
  SYSTEM = 5,
  OTHER = 6,
}
