name: Vercel Service Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.SERVICE_VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - feature/**
      - fix/**
      - hotfix/**
    paths:
      - apps/service/**
      - packages/**
  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install pnpm
        run: npm install --global pnpm@10
      - name: Install dependencies
        run: pnpm install
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build TypeScript into JavaScript
        run: pnpm run service build
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --target=preview --token=${{ secrets.VERCEL_TOKEN }}
